trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildAndDeploy
    jobs:
      - deployment: DeployApp
        displayName: Deploy App
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  submodules: true
                - task: UseNode@1
                  inputs:
                    version: 18.20.4
                - script: 'pnpm install --frozen-lockfile'
                  displayName: 'Install dependencies'
                - task: Bash@3
                  displayName: Build
                  inputs:
                    targetType: 'inline'
                    script: |
                      pnpm run build
                - task: AzureStaticWebApp@0
                  displayName: 'Deploy to SWA'
                  inputs:
                    app_location: 'blog/out'
                    api_location: 'api'
                    output_location: ''
                    skip_api_build: true
                    skip_app_build: true
                    verbose: true
                    azure_static_web_apps_api_token: $(DeploymentToken)
